//! The records, as their schemas describe them: generated by `build.rs` from
//! `standards/**/schema/*.yaml` each time a schema changes.
#![allow(non_snake_case, clippy::all)]

use serde::{Deserialize, Serialize};

/// An angle, as the registry writes it: in degrees.
#[derive(Clone, Copy, Debug, Default, PartialEq, PartialOrd, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Degrees(pub f64);

impl Degrees {
    /// In radians, as the engine works.
    pub fn rad(self) -> f64 {
        self.0.to_radians()
    }
}

/// What a record names: each reference handed to `f` with the kinds of record it may name.
pub trait Refs {
    fn refs<'a>(&'a self, f: &mut dyn FnMut(&'a str, &'static [&'static str]));
}

impl<T: Refs> Refs for Box<T> {
    fn refs<'a>(&'a self, f: &mut dyn FnMut(&'a str, &'static [&'static str])) {
        (**self).refs(f)
    }
}

include!(concat!(env!("OUT_DIR"), "/generated.rs"));
