[package]
name = "universe-engine"
edition.workspace = true
version.workspace = true

[dependencies]
universe-prof = { path = "../prof" }
wgpu.workspace = true
winit.workspace = true
glam.workspace = true
bytemuck.workspace = true
pollster.workspace = true
log.workspace = true
png = "0.18"
cpal = "0.18"
font8x8 = "0.3"
ab_glyph = "0.2"
gltf = { version = "1", default-features = false, features = ["import", "utils", "names", "KHR_materials_emissive_strength"] }
serde.workspace = true
texpresso = { version = "2.0.2", features = ["rayon"] }
rayon.workspace = true

[dev-dependencies]
universe-world = { path = "../world" }
naga = { version = "30", features = ["wgsl-in"] }
