[package]
name = "universe-world"
edition.workspace = true
version.workspace = true

# The world: content, structures, ships and their devices, world rules and
# services. Built on Dogma; knows nothing about navigation.
[dependencies]
universe-protocol = { path = "../protocol" }
universe-prof = { path = "../prof" }
universe-physics = { path = "../physics" }
glam.workspace = true
serde.workspace = true
ron = "0.12"
rayon.workspace = true

[build-dependencies]
serde.workspace = true
ron = "0.12"
