[package]
name = "universe"
edition.workspace = true
version.workspace = true

# The game: Freefall (by Plurence).
[[bin]]
name = "freefall"
path = "src/main.rs"

[dependencies]
rayon.workspace = true
universe-prof = { path = "../prof" }
universe-engine = { path = "../engine" }
glam.workspace = true
log.workspace = true
env_logger.workspace = true
universe-sim = { path = "../sim" }
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
